### ISSUE TITLE
Include git commit in version number

### ISSUE THREAD

**Issue by cgrigis** [c4dt/byzcoin#28]
Follow-up of a [discussion](https://github.com/dedis/cothority/pull/2340#discussion_r458228989):

In addition to the tag and date, I would suggest to include the git commit in the version number. This would allow to pinpoint precisely the code that is running on the conodes. Something similar to what `git describe` produces:
```$ git describe --tags
v3.4.5-85-g3ce8cc8a6
```

**Comment by ineiti** [comment]
what is the `85` in your tag? My current proposition would be to have
```
v3.4.5-200722-12345678-87654321
```
where `12345678` is the git-commit of the dedis/cothority, and `87654321` is the latest git-commit of c4dt/byzcoin... Unfortunately you need both. Except if I manage to fix https://github.com/c4dt/byzcoin/blob/master/.travis.yml#L38

**Comment by cgrigis** [comment]
> what is the `85` in your tag?

That's the "distance" in commits from the tag. In git's doc:
```
(...) it suffixes the tag name with the number of additional commits on top of the tagged object and the
abbreviated object name of the most recent commit.
```
`git describe` also prefixes the commit with a `g` to indicate a git commit.

> My current proposition would be to have
> 
> ```
> v3.4.5-200722-12345678-87654321
> ```
> 
> where `12345678` is the git-commit of the dedis/cothority, and `87654321` is the latest git-commit of c4dt/byzcoin... Unfortunately you need both. Except if I manage to fix https://github.com/c4dt/byzcoin/blob/master/.travis.yml#L38

Right, commit IDs in both repositories makes sense.

I would strongly suggest that the date use the full year though, as in "20200722" :-) . Besides me always parsing it wrong otherwise ;-) , it seems fairly universal to use 4-digit years (ISO-8601 for example [prescribes a 4-digit year](https://en.wikipedia.org/wiki/ISO_8601#Years)).

**Comment by ineiti** [comment]
OK, +1 for 4-digit year. I just discovered `git describe --tags master`...

Probably I'll try to make the `git push` work, and then only publish the c4dt/byzcoin commit. Else it's getting too big.

**Comment by cgrigis** [comment]
I am now wondering whether using the `tag` in actually relevant, since cothority releases are no longer tagged, and the tag refers to the npm release?

Also, I did not quite grasp what the problem is with the `git push`?

**Comment by ineiti** [comment]
> I am now wondering whether using the `tag` in actually relevant, since cothority releases are no longer tagged, and the tag refers to the npm release?

so `byzcoin-20200722-12345678` would be enough?

> Also, I did not quite grasp what the problem is with the `git push`?

It's the .travis.yml that tries to update and then push the update to the master branch: https://github.com/c4dt/byzcoin/blob/master/.travis.yml#L38

**Comment by cgrigis** [comment]
> so `byzcoin-20200722-12345678` would be enough?

Possibly, with one or two commit ids as discussed, and the commit ids prefixed with `g` to remove ambiguity: `byzcoin-20200722-g12345678`

> It's the .travis.yml that tries to update and then push the update to the master branch: https://github.com/c4dt/byzcoin/blob/master/.travis.yml#L38

Yes I saw that line that you referenced before. :-)
What I did not understand is what you mean by "I'll try to make the git push work"?

**Comment by ineiti** [comment]
currently the `git push` silently fails, as the repo is not updated automatically. Only the docker...
